name: Check Files

on:
  pull_request:
    branches:
      - dev
      - prod

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: "paulo/api-gitops"
      AWS_REGION: "us-east-1"
    steps:

      - name: Check out code
        uses: actions/checkout@v2
    
      - name: OK
        run: echo "Healthy"
